package com.letyouknow.retrofit

class ApiConstant {
    companion object {
        var username = "username"
        var password = "password"
        var middleName = "middleName"
        var firstName = "firstName"
        var lastName = "lastName"
        var email = "email"
        var userName = "userName"
        var phoneNumber = "phoneNumber"
        var packageList = "packageList"
        var checkedList = "checkedList"
        var productId = "productId"
        var yearId = "yearId"
        var makeId = "makeId"
        var modelId = "modelId"
        var trimId = "trimId"
        var exteriorColorId = "exteriorColorId"
        var interiorColorId = "interiorColorId"
        var zipCode = "zipCode"
        var vehicleYearID = "vehicleYearID"
        var vehicleMakeID = "vehicleMakeID"
        var vehicleModelID = "vehicleModelID"
        var vehicleTrimID = "vehicleTrimID"
        var vehicleExteriorColorID = "vehicleExteriorColorID"
        var vehicleInteriorColorID = "vehicleInteriorColorID"
        var dealerAccessoryIDs = "dealerAccessoryIDs"
        var vehiclePackageIDs = "vehiclePackageIDs"
        var ImageId = "ImageId"
        var ImageProduct = "ImageProduct"
        var searchRadius = "searchRadius"
    }
}