package com.letyouknow.model

import java.io.Serializable

data class FindLCDDeaData(
    val dealID: String? = "",
    val userID: String? = "",
    val guestID: String? = "",
    val vehicleInventoryID: String? = "",
    var price: Float? = 0.0f,
    var msrp: Float? = 0.0f,
    val zipCode: String? = "",
    val searchRadius: String? = "",
    var loanType: String? = "",
    var initial: String? = "",
    val dealTimeStamp: String? = "",
    val promotionId: String? = "",
    val timeZoneOffset: String? = "",
    val ip: String? = "",
    val canSavePayment: String? = "",
    val payment_method_id: String? = "",
    val payment_intent_id: String? = "",
    val card_brand: String? = "",
    val card_last4: String? = "",
    var productId: String? = "",
    var yearId: String? = "",
    var makeId: String? = "",
    var modelId: String? = "",
    var trimId: String? = "",
    var exteriorColorId: String? = "",
    var interiorColorId: String? = "",
    var yearStr: String? = "",
    var makeStr: String? = "",
    var modelStr: String? = "",
    var trimStr: String? = "",
    var exteriorColorStr: String? = "",
    var interiorColorStr: String? = "",
    var arPackage: String? = "",
    var arAccessories: String? = "",
    var firstName: String? = "",
    var discount: Float? = 0.0f,
    var arPackageId: ArrayList<String> = ArrayList(),
    var arAccessoriesId: ArrayList<String> = ArrayList()
) : Serializable